# Generated by Django 4.2 on 2025-09-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_address', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('weight', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
                ('shipping_type', models.CharField(max_length=100)),
                ('origin_office', models.CharField(max_length=100)),
                ('destination_office', models.CharField(max_length=100)),
                ('shipping_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='LiveUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('stages_status', models.CharField(choices=[('complete', 'complete'), ('blocked', 'blocked')], max_length=50)),
                ('stages_label', models.CharField(choices=[('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Withheld', 'Withheld'), ('Arrived', 'Arrived')], max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.countrylocation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_update', to='account.shipment')),
            ],
        ),
    ]
