# Generated by Django 4.2 on 2025-10-02 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveupdate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveupdate',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='liveupdate',
            name='stages_label',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Withheld', 'Withheld'), ('Arrived', 'Arrived')], max_length=50),
        ),
    ]
